version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    groups:
      nuget-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/infra/nginx"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    groups:
      docker-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "terraform"
    directories:
      - "/infra/terraform/environments/*"
      - "/infra/terraform/modules/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:45"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    groups:
      terraform-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
