services:
  k6:
    image: docker.io/grafana/k6:latest
    container_name: poc-k6
    working_dir: /scripts
    entrypoint: [ "k6" ]
    volumes:
      - ./loadtests/k6:/scripts:ro
      - ./artifacts/k6:/artifacts
      - ./.env.k6.auto:/.env.k6.auto:ro
    env_file:
      - ./.env.k6.auto
    networks:
      - poc-net
